---
#
# Project:: Ansible Role - manage_cloudflared
#
# Copyright 2022, Route 1337 LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Deploy and configure cloudflared

- name: Prep prereqs
  ansible.builtin.import_tasks: prereqs.yml

- name: Tune sysctl
  ansible.builtin.import_tasks: sysctl.yml

- name: Configure the cloudflared service
  ansible.builtin.import_tasks: systemd.yml
