---
#
# Project:: Ansible Role - manage_cloudflared
#
# Copyright 2022, Route 1337 LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Manage prerequisites for this role

- name: Download cloudflared GPG key
  get_url:
    url: https://pkg.cloudflare.com/pubkey.gpg
    dest: /usr/share/keyrings/cloudflared.gpg_armored

- name: De-Armor and install Docker GPG key
  shell: "gpg --dearmor < /usr/share/keyrings/cloudflared.gpg_armored > /usr/share/keyrings/cloudflared.gpg"
  args:
    creates: /usr/share/keyrings/cloudflared.gpg

- name: Add the cloudflared repository
  apt_repository:
    repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/cloudflared.gpg] https://pkg.cloudflare.com/ {{ ansible_distribution_release }} main'
    state: present
    update_cache: yes

- name: Install cloudflared
  ansible.builtin.apt:
    name: cloudflared
    state: present

- name: Configure cloudflared directory
  ansible.builtin.file:
    path: "/etc/cloudflared"
    owner: root
    group: root
    mode: 0755
    state: directory
