---
#
# Project:: Ansible Role - manage_cloudflared
#
# Copyright 2022, Route 1337 LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Configure SystemD to enable and start cloudflared

- name: Install cloudflared (file managed) as a service
  command:
    cmd: 'cloudflared service install'
    creates: '/etc/systemd/system/cloudflared.service'
  when: manage_cloudflared.console_token is not defined
  register: cloudflared_service
  notify:
    - reload systemd

- name: Install cloudflared (ZTA managed) as a service
  command:
    cmd: 'cloudflared service install {{ manage_cloudflared.console_token }}'
    creates: '/etc/systemd/system/cloudflared.service'
  when: manage_cloudflared.console_token is defined
  register: cloudflared_service
  notify:
    - reload systemd

- name: Run handlers now to reload SystemD
  meta: flush_handlers

- name: Start and enable cloudflared
  service:
    name: cloudflared
    enabled: true
    state: restarted
