---
#
# Project:: Ansible Role - manage_cloudflared
#
# Copyright 2022, Route 1337 LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Configure SystemD to enable and start cloudflared

- name: Check if the systemd service already exists
  ansible.builtin.stat:
    path: /etc/systemd/system/cloudflared.service
  register: service_status

- name: Read the contents of the existing systemd service
  ansible.builtin.slurp:
    src: /etc/systemd/system/cloudflared.service
  register: service_contents
  when: service_status.stat.exists
  no_log: true

- name: Check if the service has an up to date token
  ansible.builtin.set_fact:
    service_contains_token: "{{ manage_cloudflared.console_token in (service_contents['content'] | b64decode) }}"
  when: service_status.stat.exists
  no_log: true

- name: Remove the old cloudflared service
  ansible.builtin.command:
    cmd: 'cloudflared service uninstall'
    removes: '/etc/systemd/system/cloudflared.service'
  when:
    - service_status.stat.exists
    - not service_contains_token | default(true)

- name: (Re)install cloudflared as a service
  ansible.builtin.command:
    cmd: 'cloudflared service install {{ manage_cloudflared.console_token }}'
    creates: '/etc/systemd/system/cloudflared.service'
  notify: Reload systemd
  no_log: true

- name: Run handlers now to reload SystemD
  ansible.builtin.meta: flush_handlers

- name: Start and enable cloudflared
  ansible.builtin.service:
    name: cloudflared
    enabled: true
    state: restarted
