---
#
# Project:: Ansible Role - manage_cloudflared
#
# Copyright 2022, Route 1337 LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Handlers used for various tasks in this role

# Handlers for systemd
- name: reload systemd
  systemd:
    daemon_reload: true
    no_block: false

- name: restart cloudflared
  service:
    name: cloudflared
    state: restarted
