---
#
# Project:: Ansible Role - manage_cloudflared
#
# Copyright 2022, Route 1337 LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Handlers used for various tasks in this role

# Handlers for systemd
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
    no_block: no

- name: restart cloudflared
  ansible.builtin.service:
    name: cloudflared
    state: restarted
